/**
 * Contents for files seeded into the simulated filesystem.
 *
 * /cv has no Next.js route on purpose — it falls through to the 404 page, which
 * is this shell. So the CV has to be findable here: `ls` then `cat resume.md`.
 * Regenerated by ~/Gits/resume/sync_files_ts.py (run `resume --general`).
 */

export const RESUME_MD = `Mohamad Khawam
New Jersey, United States
Khawammohamad99@gmail.com  |  (862)-285-1846

  github.com/mkhawam
  linkedin.com/in/mohamad-k
  mohamadk.com

Tip: run \`resume\` to open the PDF version.

== SUMMARY ==

Backend and platform engineer. I lead engineering on codePost, the grading
platform Rutgers CS runs for 1,950+ students, graders, and instructors: I
rebuilt its autograder, built its AI features and cost tracking, and keep it
running with the sysadmin team. I care most about concurrency, isolation,
security, and accessibility, and about building what the people using a system
actually ask for.

== EXPERIENCE ==

Rutgers University — Application Developer (Software Engineer)
                                                           June 2025 - Present
  * Lead engineer on codePost, the grading platform Rutgers CS runs for 1,950+
    students, graders, and instructors, which other institutions have asked to
    self-host. I own the backend, shape what ships by watching how instructors
    and graders use it, and wrote the docs the team deploys from.
  * Drive AI tooling adoption across the team: moved three sysadmins from chat
    web UIs to CLI agents that gather host data over SSH and draft deployment
    plans for them, wrote the agent rules both codePost repos share, and
    mentor a colleague on AI-assisted development.
  * Took autograder adoption from three courses to five in a semester by
    rebuilding it after instructors found the inherited one hard to use;
    submissions now run in isolated containers across seven languages and
    Jupyter notebooks.
  * Brought codePost's frontend to WCAG 2.1 AA for the ADA Title II deadline
    and built the monthly scanner that audits the ~100 websites LCSR is
    responsible for and emails each owner their issues with fixes; many have
    since been fixed.
  * Reworked the grading console with the graders who use it: reusable comment
    templates after they said feedback on simple assignments was mostly copy-
    paste, keyboard navigation, inline code execution, and AI-drafted
    comments.
  * Built the platform's AI grading assistance, from comment drafts graders
    can accept or edit to per-token cost tracking, so every course can see
    exactly what its AI usage costs and run on its own rates.
  * Automated recovery across the platform: autograder images verify, promote,
    and roll back on their own, unhealthy containers restart themselves, and
    deploys go out in health-gated stages. Grew the backend test suite from
    106 tests to 984.
  * Found and fixed a directory traversal in dataset uploads, authorization
    gaps that let students run code and read unreleased feedback, and an email
    loop that could exhaust a worker.

Rutgers University — Student Lab Technician            January 2023 - May 2025
  * Ran 10 Hackerspace workspaces that drew about 60 students a semester, most
    of them asking about the AI projects on display; wrote the student-facing
    documentation and maintained the WordPress site.
  * Built two of those demos: a Raspberry Pi computer-vision station on
    MediaPipe used for walk-in workshops, and an Express and React playground
    for AI bots.
  * Built the LED matrix sign the Hackerspace still runs today, with a web-
    based pixel and GIF editor and a display schedule.
  * Built a 3D printer monitoring service (Express and React) streaming live
    video of the printer bay so students could check job status without
    walking over.

Swish — Full-Stack Developer                         July 2021 - December 2021
  * Built the tooling Swish used to create and manage about 500 accounts
    across web platforms: Puppeteer automation driven from a Node.js CLI, with
    Mocha regression tests covering each platform's signup flow.
  * Turned the CLI into an Electron desktop app so staff who didn't want a
    terminal could manage accounts themselves.

C-Tech — Computer Technician                         July 2019 - December 2021
  * Ran the repair desk: Windows installs, malware removal, and
    troubleshooting for walk-in customers, plus a secure drive-erasure
    workflow that supported 3 enterprise clients.
  * Automated the Windows build with PowerShell scripts, cutting setup from 40
    to 20 minutes per machine.

== SKILLS ==

Languages: Python, TypeScript, JavaScript, C, Java, SQL, Bash, PowerShell

Frameworks: Django, Django REST Framework, Django Channels, Celery, Flask,
Node.js, Express, React, Next.js, JupyterLab, Electron

Data: MariaDB / InnoDB, MongoDB, Redis, Django ORM, Schema Design and
Migrations, Query Optimization and Indexing, Caching

Infrastructure: Docker, Docker Compose, Ansible, Nginx, Linux, systemd,
Proxmox, VMware, OpenStack, GitHub Actions, GitLab CI, CI/CD, Zabbix

Security: Application Security, OWASP Top 10, RBAC / ABAC Authorization,
Sandboxing and Container Isolation, CAS / Kerberos / Azure AD SSO, JWT and API
Key Management, Suricata, pfSense, Wazuh

Testing: pytest, Vitest, Jest, Playwright, Mocha, axe-core, Molecule, WCAG 2.1
AA

AI: OpenAI and Gemini APIs, Ollama, LLM Cost Metering, Tool-Calling Agents

== PROJECTS ==

CompLock                                            November 2023 - March 2024
  https://github.com/rusec/CompLock
  * Built SSH command-and-control software for networked computers in
    TypeScript on LevelDB and SSH2, used by RUSEC for one CCDC season.
  * Cut password rotation across 30 machines from 5 minutes to 30 seconds,
    with Mocha tests running in GitHub Actions.

mohamadk.com                                              April 2025 - Present
  https://mohamadk.com
  * Designed and built a Next.js 16 / React 19 portfolio and blog with a
    markdown publishing pipeline, PWA support, and a keyboard command palette.
  * Built an in-browser code playground on WebContainers that boots Node.js
    client-side to run my published ts-declaration-json package live.
  * Wrote a simulated Linux shell in TypeScript (filesystem, users, coreutils)
    that serves as the site's 404 page, plus an AI task-planning agent with
    tool calling.

Accessibility Scanner                                           2025 - Present
  https://github.com/rutgers-lcsr/Accessibility_Scanner
  * Built the monitor LCSR uses for ADA Title II compliance in place of a
    spreadsheet of sites: a Flask API and Next.js interface drive Playwright
    and axe-core scans through Celery workers across the ~100 websites the
    department is responsible for, deployed through an Ansible role I wrote.
  * Scans every site monthly and emails the responsible faculty member a
    report with each issue linked to its fix, since the department tracks the
    sites but their owners fix them; many have since been fixed.
  * Added an endpoint that hands an AI agent a page's issues and the context
    to fix them, so a site owner can point an agent at their app and the
    scanner and have it work through the problems.
  * Stores per-page results with screenshots so remediation progress is
    measurable over time.

== EDUCATION ==

Bachelor of Arts — Computer Science                                   May 2025
  * Rutgers University. Coursework: Computer Security, Software Methodology,
    Computer Architecture.

== CERTIFICATIONS ==

AWS Certified Cloud Practitioner — Amazon Web Services
                                      January 2025, valid through January 2028

== LEADERSHIP ==

RUSecurity (Student Cybersecurity Club) — Vice President
                                                       January 2023 - May 2025
  * Managed network administration for the 12-person CCDC team, which placed
    4th of 10 teams in 2024.
  * Led club infrastructure setup on Proxmox and VMware ESXi, standing up the
    practice range the team trained on.
  * Led development of the club's BlackBox machine environment with Wazuh
    detection rules and the ToolBox hardening toolkit used for CCDC
    preparation.
`;

export const README_MD = `# personal-site

Personal site and blog for Mohamad Khawam.

Built with Next.js, Tailwind CSS, and DaisyUI. The 404 page is a simulated
Linux shell — you are inside it right now.

## Getting started

    npm install
    npm run dev

## Layout

    posts/    markdown blog posts
    public/   static assets
    src/app/  routes and components
    src/app/unix/  this shell

Try: ls, cd, cat, whoami, uname, ping, sl, resume, help
`;

export const PACKAGE_JSON = `{
  "name": "personal-site",
  "version": "0.2.0",
  "private": true,
  "scripts": {
    "dev": "next dev --turbopack --port 3001 --experimental-https",
    "build": "next build",
    "start": "next start"
  }
}
`;
